# Default values for crypto-nodeapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

appName: cryptoNodeapp
name: crypto-nodeapp
version: v1

image:
  repository: shaktibxr/nodeapp
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  name: crypto-nodeapp
  protocol: TCP
  port: 4000
  nodePort: 4000

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}
